# -*- coding: utf-8 -*-
"""Python Module End Assignment .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqcymR9SizVOoOqe8K8VK2W50IsD_VZT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

uploaded = files.upload()

df = pd.read_csv(next(iter(uploaded.keys())))

df['height'] = np.random.randint(150, 181, size=len(df))
print(df.info())

#1. Determine the distribution of employees across each team and calculate the percentage split relative to the total number of employees.
teamd = df['Team'].value_counts()
teamp = (td / df.shape[0]) * 100
print(td)

plt.figure(figsize=(10, 6))
plt.bar(teamd.index, teamd.values)
plt.title('Distribution of Employees Across Teams')
plt.xlabel('Team')
plt.ylabel('Number of Employees')
plt.xticks(rotation=90)
plt.show()

"""#Team New Orleans Pelicans has most number of employees(19 employees).Most of the teams having 15 employees"""

#2.Segregate employees based on their positions within the company
position = df['Position'].value_counts()
print("Position Distribution:")
print(position)

plt.figure(figsize=(10, 6))
plt.bar(position.index, position.values)
plt.title('Distribution of Employees by Position')
plt.xlabel('Position')
plt.ylabel('Number of Employees')
plt.show()

"""#Most employess are in position SG(there 102 employees in the sg position).Least employees are in the position c."""

# 3. Identify the predominant age group among employees

bins = [20, 30, 40, 50, 60]
labels = ['20-30', '30-40', '40-50', '50-60']
df['age_group'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)
ad = df['age_group'].value_counts()
print("Age Group Distribution:")
print(ad)

plt.figure(figsize=(10, 6))
plt.bar(ad.index.astype(str), ad.values)
plt.title('Age Group Distribution')
plt.xlabel('Age Group')
plt.ylabel('Number of Employees')
plt.show()

"""#The predominant age group is 20-30 with 334 employees.from that we can realise that most of the employees are young.and there is no employee is in the age above 50.This company is having employees under age 50"""

# 4. Discover which team and position have the highest salary expenditure
team_salary = df.groupby('Team')['Salary'].sum()
print("Salary Expenditure by Team:")
print(team_salary)

plt.figure(figsize=(10, 6))
plt.bar(team_salary.index,team_salary.values)
plt.title('Salary Expenditure by Team')
plt.xlabel('Team')
plt.ylabel('Total Salary')
plt.xticks(rotation=90)
plt.show()

position_salary= df.groupby('Position')['Salary'].sum()
print("Salary Expenditure by Position:")
print(position_salary)

plt.figure(figsize=(10, 6))
plt.bar(position_salary.index,position_salary.values)
plt.title('Salary Expenditure by Position')
plt.xlabel('Position')
plt.ylabel('Total Salary')
plt.show()

"""#Team atlanta hawks is the team with highest salary.Emplyees in the c position is having highest salary"""

# 5.  Investigate if there's any correlation between age and salary, and represent it visually.
correlation = df[['Age', 'Salary']].corr()
print("Correlation between Age and Salary:")
print(correlation)

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='Age', y='Salary')
plt.title('Correlation Between Age and Salary')
plt.xlabel('Age')
plt.ylabel('Salary')
plt.show()
#in this correlation between age and salary ,it shws that initially as age increases salary also increase till age reaches between 30-35 and after that there is a trend in decrease of salary as the age increase..

"""#From the correlation we can realise that when the age increases salary also increasing.from that we can understand that experienced person is getting more salary.But the company is preffering young emplooyes so aged employees are getting less salary."""